### ISSUE TITLE
The class cannot calculate the elapsed time

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-filter-elapsed#2]
The current object in the logstash/timestamp class doesn't support operators.
The elapsed time is calculated with two instances of timestamp, we could apply an integer conversion to fix for this, but It is better to change how the original class behave.

The fix is in https://github.com/elasticsearch/logstash/pull/2061

**Comment by wiibaa** [comment]
@ph as mentionned issue is merged in core, is it still something to be done regarding this issue ?

**Comment by jsvd** [comment]
fixed by elastic/logstash#2061, this is already included in 1.5.0
