### ISSUE TITLE
Filter seems to ignore timeout value 

### ISSUE THREAD

**Issue by pandaadb** [logstash-plugins/logstash-filter-elapsed#22]
Hi,

after a few hours of experimentation I think there may be an issue with the timeout value. I am trying to calculate the elapsed time between two of my events. I have two scenarios: 
1. First event and Second event are less than  20 seconds apart (immediate execution). These are the ones I want to measure
2. First and Second event minutes apart - this happens when something is scheduled and I want it to be ignored. 

So I set my config to timeout events > 20 seconds. However, all events match and nothing is filtered. 

This is my config: 

```
input {

    stdin{
            "add_field" =>  { "client" => "test" }
    }

}

filter {


        multiline {
                pattern => "^\[%{LOGLEVEL}\]"
                negate => true
                what => "previous"
        }

        grok {
            break_on_match => false
            patterns_dir => "/Users/artur/dev/logstash/config/patterns"
            match => {
                "message" => "\[%{LOGLEVEL:level}\] \[%{IPORHOST:from}\] %{TIMESTAMP_ISO8601:timestamp} \[%{DATA:thread}\] \[%{NOTSPACE:logger}\] %{GREEDYDATA:msg}"
            }
            #remove_tag => ["_grokparsefailure"]
            #named_captures_only => false
        }

        date {
            locale => "en"
            match => ["timestamp", "ISO8601"]
            timezone => "UTC"
            target => "@timestamp"
            add_field => { "debug" => "timestampMatched"}
        }

        mutate
        {
         remove_field => [ "timestamp"]
        }


        grok {
            match => {
                "msg" => "START\: Received schedule request for\: \(%{GREEDYDATA:task_id}\)"
            }
            add_tag => [ "taskStarted" ]
            tag_on_failure => [ ]
        }

        grok {
            match => {
                "msg" => "END\: Poking:.* for Key: \(%{GREEDYDATA:task_id}\)"
            }
            add_tag => [ "taskEnded" ]
            tag_on_failure => [ ]
        }

        elapsed {
            start_tag => "taskStarted"
            end_tag => "taskEnded"
            unique_id_field => "task_id"
            timeout => 2050        
        }


}

output {
    stdout {
            codec => "rubydebug"
    }
}
```

Here is the input I am using:

```
[INFO] [SomeId] 2016-02-26T15:34:06.179Z [message-inserter-1] [ClassA] START: Received schedule request for: (test) Scheduled: 2016-02-26T15:34:00
[INFO] [SomeId2] 2016-02-26T16:08:00.813Z [message-sender-3] [ClassB] END: Poking: {"message"} for Key: (test)
```

Here is the output that I am seeing: 

```
Logstash startup completed
[INFO] [SomeId] 2016-02-26T15:34:06.179Z [message-inserter-1] [ClassA] START: Received schedule request for: (test) Scheduled: 2016-02-26T15:34:00
[INFO] [SomeId2] 2016-02-26T16:08:00.813Z [message-sender-3] [ClassB] END: Poking: {"message"} for Key: (test)
{
       "message" => "[INFO] [SomeId] 2016-02-26T15:34:06.179Z [message-inserter-1] [ClassA] START: Received schedule request for: (test) Scheduled: 2016-02-26T15:34:00",
      "@version" => "1",
    "@timestamp" => "2016-02-26T15:34:06.179Z",
        "client" => "test",
          "host" => "arturk.local",
         "level" => "INFO",
          "from" => "SomeId",
        "thread" => "message-inserter-1",
        "logger" => "ClassA",
           "msg" => "START: Received schedule request for: (test) Scheduled: 2016-02-26T15:34:00",
         "debug" => "timestampMatched",
       "task_id" => "test",
          "tags" => [
        [0] "taskStarted"
    ]
}
{
                    "message" => "[INFO] [SomeId2] 2016-02-26T16:08:00.813Z [message-sender-3] [ClassB] END: Poking: {\"message\"} for Key: (test)",
                   "@version" => "1",
                 "@timestamp" => "2016-02-26T16:08:00.813Z",
                     "client" => "test",
                       "host" => "arturk.local",
                      "level" => "INFO",
                       "from" => "SomeId2",
                     "thread" => "message-sender-3",
                     "logger" => "ClassB",
                        "msg" => "END: Poking: {\"message\"} for Key: (test)",
                      "debug" => "timestampMatched",
                    "task_id" => "test",
                       "tags" => [
        [0] "taskEnded",
        [1] "elapsed",
        [2] "elapsed_match"
    ],
               "elapsed_time" => 2034.634,
    "elapsed_timestamp_start" => "2016-02-26T15:34:06.179Z"
}
```

As you can see, the elapsed time is 2034 seconds, which is the difference between the timestamps, so the time has been calculated correctly. However, the timeout hasn't kicked in.

**Comment by cbarbaza** [comment]
Hi,

I have same issue, I set the timeout to 15 seconds and I got elapsed_time over than this value...

Do you have any idea ?

**Comment by pandaadb** [comment]
I think this plugin is no longer supported (?) .. i will look into this the next few weeks if i find a minute and see if i can fix it in a clone and create a pull request

**Comment by pandaadb** [comment]
It appears periodic flush is not enabled, meaning that flush is never called by logstash and the filter never expires old events. 

source for the base: https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/filters/base.rb

will create a pull request shortly

**Comment by pandaadb** [comment]
@cbarbaza no not yet. I have to test some things still and the PR needs to be reviewed, approved, merged and released which all depends on the maintainer of this plugin

**Comment by pandaadb** [comment]
@cbarbaza 

I did a few tests and i am right with my assumption.

There is a workaround for this issue that I just tested. the issue is, as stated, that the period flush is not enabled by default within logstash. since the filter adapts the default value, expiry isn't working. (I by the way believe that this also causes memory errors when reparsing a massive amount of events which is happening for me right now).

you can work around this issue by setting:

```
elapsed {
    periodic_flush => true
    start_tag => "taskStarted"
    end_tag => "end"
    unique_id_field => "id"
    timeout => 1
    new_event_on_match => true
  }

```

The important part is 

`periodic_flush => true`

This tells logstash to call the flush method which then expires events. Tested it and it works.

Regards,

Artur

**Comment by michaeleino** [comment]
@pandaadb , you are right... but calling the flush filter cases the plugin to drop all events expired & not expired....
It seems firstly to work, but after having a lot of logs (hundreds) it drops all
Any further work around ?

**Comment by nerophon** [comment]
This actually causes a memory leak when the filter is used and ingest is high. Definitely worth a fix.

**Comment by colinsurprenant** [comment]
With #36 the `periodic_flush` option is now defaulted to `true` which is required for the cache expiration to work. You can either upgrade to v4.0.5 or add option
```
elapsed {
  ...
  periodic_flush => true
}
```

I will close this issue, please open a new one if there are other problems.
