### ISSUE TITLE
Hand over fields from the start event to the end event

### ISSUE THREAD

**Issue by elvarb** [logstash-plugins/logstash-filter-elapsed#23]
I have a event stream where the start event contains details of the process and the end event only contains that it ended. With the elapsed filter the time is added to the end event. This makes it impossible to view everything in a single event.

**Comment by muellerc** [comment]
I'm using the aggregate filter plugin (https://www.elastic.co/guide/en/logstash/current/plugins-filters-aggregate.html) to do this.

**Comment by elvarb** [comment]
That filter would work :)
