### ISSUE TITLE
Current version not supported by Logstash version 5

### ISSUE THREAD

**Issue by il-bert** [logstash-plugins/logstash-filter-elapsed#25]
Current version of plugin is not compatible with logstash 5.x, during installation phase it looks for a logstash of version 2.x, if not present it fails.

**Comment by janisp** [comment]
I can confirm, that I am experiencing the same issue

**Comment by marvink87** [comment]
+1

**Comment by jordansissel** [comment]
Please don't write `+1` comments. Doing so creates hundreds of emails with no real content. Please use github's "reaction" feature instead, if you feel you need to provide a +1.

**Comment by aeva-assured** [comment]
Saw the new notes that API v5.0 was merged yesterday. I'm getting errors trying to install the plugin via ./logstash-plugin install elapsed

This is a fresh install of logstash 5.0.2-1

> bin]$ sudo ./logstash-plugin install elapsed
>Validating elapsed
>Plugin elapsed does not exist
>ERROR: Installation aborted, verification failed for elapsed

Does the new version specifically need to be pulled from Git? Apologies for using the existing issue, but seemed relevant as it appears to resolve the overall issue of v5 support.

**Comment by suyograo** [comment]
do `bin/logstash-plugin install logstash-filter-elapsed`

**Comment by suyograo** [comment]
Published v4.0.0 of this plugin to be compatible with LS 5.0.0
